Si estás agradecido con nuestras herramientas y te han sido de utilidad, te invitamos a considerar hacer una pequeña donación para invitarnos a un café. Esta contribución nos ayudará a seguir mejorando nuestras herramientas y a ofrecer un mejor soporte a nuestra comunidad. Tu generosidad y apoyo significan mucho para nosotros y nos motiva a seguir trabajando en nuevas soluciones y actualizaciones. ¡Gracias por considerar apoyarnos con una donación y por ser parte de nuestra comunidad!


Ethereum (ETH) Address: 0x7eF78Db0c72114B7510bdb9fB993F4b0A571EAa2


Bitcoin (BTC) Address:
bc1qlswghxl7pnf6q8a8vzkvre7v8ayhcyr2kuwv6h

XRP (XRP) Address:
rbY8XFaNmsVY4N6377dmqeZSHAwxMW

Cardano (ADA) Address: addr1qyl23s902zgg5p9z3w29ah2fjd5s3qns6edlgcw8wp889c374rq275ys3gz29zu5tmw5nymfpzp8p4jm73suwuzwwt3qlch98p

Solana (SOL) Address: 2dhzmM8xJNeuKTWKFfgchCuYfHXeSNm4isF7iayNY3jp

Dogecoin (DOGE) Address:
DEjw3swpoifUzS69ZYSGV5aoQUagYuGpDq

Tron (TRX) Address:
THAtJW5bp1KDoRvgukJDKJ1v8UDyccBu4s
---------------------------------------------------------------

//@version=4
study(title="SatoshiAlpha 01", overlay = true)

// Inputs
a = input(1,     title = "Key Vaule. 'This changes the sensitivity'")
c = input(10,    title = "ATR Period")
h = input(false, title = "Signals from Heikin Ashi Candles")

// EMA Inputs
ema1_length = input(21, title="EMA 1 Length", minval=1)
ema2_length = input(55, title="EMA 2 Length", minval=1)
ema3_length = input(200, title="EMA 3 Length", minval=1)

// RSI Input
rsi_length = input(30, title="RSI Length", minval=1)

xATR  = atr(c)
nLoss = a * xATR

src = h ? security(heikinashi(syminfo.tickerid), timeframe.period, close, lookahead = false) : close

xATRTrailingStop = 0.0
xATRTrailingStop := iff(src > nz(xATRTrailingStop[1], 0) and src[1] > nz(xATRTrailingStop[1], 0), max(nz(xATRTrailingStop[1]), src - nLoss),
    iff(src < nz(xATRTrailingStop[1], 0) and src[1] < nz(xATRTrailingStop[1], 0), min(nz(xATRTrailingStop[1]), src + nLoss),
    iff(src > nz(xATRTrailingStop[1], 0), src - nLoss, src + nLoss)))

// EMAs
ema1 = ema(src, ema1_length)
ema2 = ema(src, ema2_length)
ema3 = ema(src, ema3_length)

// RSI
rsi = rsi(src, rsi_length)

// Buy and Sell Conditions
aboveEMAs = src > ema1 and src > ema2 and src > ema3
belowEMAs = src < ema1 and src < ema2 and src < ema3

buy = aboveEMAs and crossover(src, xATRTrailingStop) and rsi > 50
sell = belowEMAs and crossover(xATRTrailingStop, src) and rsi < 50

// Plotting EMAs
plot(ema1, color=color.blue, linewidth=2, title="EMA 1")
plot(ema2, color=color.orange, linewidth=2, title="EMA 2")
plot(ema3, color=color.red, linewidth=2, title="EMA 3")

// Plotting Buy/Sell Signals
plotshape(buy,  title = "Buy",  text = 'Buy',  style = shape.labelup,   location = location.belowbar, color= color.green, textcolor = color.white, transp = 0, size = size.tiny)
plotshape(sell, title = "Sell", text = 'Sell', style = shape.labeldown, location = location.abovebar, color= color.red,   textcolor = color.white, transp = 0, size = size.tiny)

// Bar Colors
barcolor(buy  ? color.green : na)
barcolor(sell ? color.red   : na)
GcSGX6PQQ5KMSaP
// Alerts
// Alerts
alertcondition(buy,  "Long",  "Long")
alertcondition(sell, "Short", "Short")

console.log("hello");